#!/bin/bash -e

export DEBUG_FLAG=""
export SSH_KEY=""

while [[ $# -gt 0 ]]; do
  case "${1}" in
  --sshkey)
    echo "SSHKEY detected (remaining: ${#})"
    [[ "${2}" == "" ]] && echo "expected ssh algorithm missing"
    [[ "${3}" == "" ]] && echo "expected ssh key missing"
    [[ "${4}" == "" ]] && echo "expected ssh suffix missing"
    export SSHKEY="${2} ${3} ${4}"
    echo "SSHKEY: ${SSHKEY}"
    shift # past argument
    shift # past value
    ;;
  --debug)
    echo "DEBUG mode active (remaining: ${#})"
    export DEBUG_FLAG="--debug"
    shift # past argument
    [[ $# -gt 0 ]] && shift # past value
    ;;
  --*)
    echo "Unknown option ${1}"
    exit 1
    ;;
  *)
    shift # past argument
    ;;
  esac
done

if [[ "${DEBUG_FLAG}" == "--debug" ]]; then
  echo "operation: 'proxy', name: '${1}'  (this: $0)"
fi

/git/git-shell-commands/authorize.py ${DEBUG_FLAG} --sshkey "${SSHKEY}"

exit $?
