#!/bin/bash -e
AUTHORIZED_KEYS_FILE=/git/.ssh/authorized_keys
SUPPORTED_ALGORITHMS="ssh-rsa|ssh-dss|ecdsa-sha2-nistp256|ecdsa-sha2-nistp384|ecdsa-sha2-nistp521|ssh-ed25519"
regex="^((${SUPPORTED_ALGORITHMS}) AAAA[0-9A-Za-z+/]+[=]{0,3}( [^@]+@[^@]+)?)"

public_key="${1}"

if [[ $public_key =~ $regex ]]; then
  echo "${public_key}" >>"${AUTHORIZED_KEYS_FILE}"
  exit 0
else
  echo "Invalid public ssh key"
  echo ""
  echo "Be sure to use a supported algorithm.  The following are supported."
  for alg in $(echo ${SUPPORTED_ALGORITHMS} | tr '|' ' '); do
    echo "  ${alg}"
  done
  echo ""
  exit 1
fi
