#!/bin/bash -e

BASE_DIR="/git/repos"

echo "git repo delete...."
# shellcheck disable=SC2001
repo="""${BASE_DIR}/$(echo "${1}" | sed -e 's/\.\.//g' | sed -e 's/\/\//\//g')"""

if [[ -d "${repo}.git" ]]; then
  echo "removing ${1}"
  here="${repo}"
  while [[ "${here}" != "${BASE_DIR}" ]]; do
    echo "removing ${here}"
    rm -rf "${here}" || exit 2
    rm -rf "${here}.git" || exit 3
    echo "here: ${here}"
    here="""$(dirname "${here}")"""
  done
  exit 0
else
  echo "no repo exists named ${1}"
  exit 1
fi
