#!/bin/bash -e

BASE_DIR="/git/repos"

echo "git repo delete...."
# shellcheck disable=SC2001
repo="""${BASE_DIR}/$(echo "${1}" | sed -e 's/\.\.//g' | sed -e 's/\/\//\//g').git"""

if [[ -d "${repo}" ]]; then
  echo "removing ${1}"
  rm -rf "${repo}" || exit 3
  find /git/repos/ -type d -not -path '*/*.git/*' -empty -delete
  exit 0
else
  echo "no repo exists named ${1}"
  exit 1
fi

