#!/bin/bash -e
echo '

git-shell...

authorize  - authorize a new ssh key
authorized - return the enumerated list of ssh keys
create     - create a new repo
delete     - delete existing repository
help       - this screen
list       - list the repositories in the server
proxy      - clone a remote repository to this server as a proxy
push-proxy - push changes in this server to the remote proxied repository
rename     - rename a repository.

'
